name: Main GitHub Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Compile the app
      run: npm install --production

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check the coding style (Lint)
        run: |
          tslint src/*.ts{,x}
          tslint src/**/*.ts{,x}
